---
title: "Spatial Autocorrelation"
output: html_notebook
---
```{r}
library(sf)     
library(dplyr)   
library(spData) 
library(ggplot2)
library(ggthemes)
#Let's load in some packages and data
setwd("C:\\Users\\laure\\OneDrive\\Desktop\\DIDA 425 Project\\nyc_shapefile")
```
```{r}
nyc <- st_read("NYC_Tract_ACS2008_12.shp")
```

```{r}
#plotting the data first
ggplot()+
  geom_sf(data = nyc, aes(fill=poor))+
  scale_fill_steps(
    name = "Number of \nPoor Households",
    low = "lightsteelblue1",
    high = "tomato1",
    n.breaks = 4,
    show.limits = T)+
  theme_void()
```

```{r}
# Was this map created using a spatially random process? (CSR)
nyc_list <- nyc %>% 
  #first convert polygons to a neighbor object
  #R needs to know a unique ID for each neighborhood    
  #(cartodb_id)
  #Neighbors determined using Queen weights
  poly2nb(st_geometry(nyc), row.names = nyc$cartodb_id) %>% 
  #zero.policy just tells R not to remove 0 values
  nb2listw(zero.policy = TRUE)
```

```{r}

```

